sudo: false
dist: trusty
language: node_js
node_js:
  - "4"
env:
    - EMBER_VERSION=2.11.1

cache:
  directories:
    - "client/node_modules"

before_install:
    # setting the path for phantom.js 2.0.0
    - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - "npm config set spin false"
    - "npm install -g npm@^2"
install:
    - npm install babel-plugin-transform-es2015-block-scoping
    - npm install -g bower
    - make deps
script:
    - make check
    - make test