sudo: false
dist: trusty
language: node_js
node_js:
  - "12"
env:
    - EMBER_VERSION=3.20.0
addons:
  chrome: stable

cache:
  directories:
    - "client/node_modules"

before_install:
    - "npm config set spin false"
    - "npm install -g npm@^6"
install:
    - npm install babel-plugin-transform-es2015-block-scoping
    - npm install -g bower
    - make deps
script:
    - make check
    - make test